# Generated by Django 3.1.6 on 2021-03-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default='https://github.com/mulherinstephen/avalanche/blob/main/teton_DEM.ipynb', max_length=250),
            preserve_default=False,
        ),
    ]
